language: python
env:
  - DATABASE_URL="dbname='stackoverflow_lite' host='127.0.0.1' port='5432' user='postgres' password=''"
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
   - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE stackoverflow_lite' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres
  - python from app import db; db.create_all()

script:
  - nosetests tests -v --with-coverage --cover-package=app

after_success:
  - coveralls