language: python
env:
  - DATABASE_URL=postgres://postgres:@127.0.0.1:5432/stackoverflow_lite
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
   - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE stackoverflow_lite' -U postgres
  - psql -f ddl.sql stackoverflow_lite
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres

script:
  - nosetests tests -v --with-coverage --cover-package=app

after_success:
  - coveralls